
package OrderServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderServiceImpl", targetNamespace = "http://OrderService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns OrderServiceClient.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderById", targetNamespace = "http://OrderService/", className = "OrderServiceClient.GetOrderById")
    @ResponseWrapper(localName = "getOrderByIdResponse", targetNamespace = "http://OrderService/", className = "OrderServiceClient.GetOrderByIdResponse")
    @Action(input = "http://OrderService/OrderServiceImpl/getOrderByIdRequest", output = "http://OrderService/OrderServiceImpl/getOrderByIdResponse")
    public Order getOrderById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
