
package OfferServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import courierservice.Courier;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OfferServiceImpl", targetNamespace = "http://OfferService/")
@XmlSeeAlso({
    courierservice.ObjectFactory.class,
    OfferServiceClient.ObjectFactory.class
})
public interface OfferServiceImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns OfferServiceClient.TransportServiceOffer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOffer", targetNamespace = "http://OfferService/", className = "OfferServiceClient.GetOffer")
    @ResponseWrapper(localName = "getOfferResponse", targetNamespace = "http://OfferService/", className = "OfferServiceClient.GetOfferResponse")
    @Action(input = "http://OfferService/OfferServiceImpl/getOfferRequest", output = "http://OfferService/OfferServiceImpl/getOfferResponse")
    public TransportServiceOffer getOffer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Order arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculatePrice", targetNamespace = "http://OfferService/", className = "OfferServiceClient.CalculatePrice")
    @ResponseWrapper(localName = "calculatePriceResponse", targetNamespace = "http://OfferService/", className = "OfferServiceClient.CalculatePriceResponse")
    @Action(input = "http://OfferService/OfferServiceImpl/calculatePriceRequest", output = "http://OfferService/OfferServiceImpl/calculatePriceResponse")
    public double calculatePrice(
        @WebParam(name = "arg0", targetNamespace = "")
        Courier arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Order arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateOfferId", targetNamespace = "http://OfferService/", className = "OfferServiceClient.GenerateOfferId")
    @ResponseWrapper(localName = "generateOfferIdResponse", targetNamespace = "http://OfferService/", className = "OfferServiceClient.GenerateOfferIdResponse")
    @Action(input = "http://OfferService/OfferServiceImpl/generateOfferIdRequest", output = "http://OfferService/OfferServiceImpl/generateOfferIdResponse")
    public String generateOfferId();

}
