
package OrderShipmentServiceClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderShipmentServiceImpl", targetNamespace = "http://OrderShipmentService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderShipmentServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<OrderShipmentServiceClient.OrderShipment>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "insertOrderShipment", targetNamespace = "http://OrderShipmentService/", className = "OrderShipmentServiceClient.InsertOrderShipment")
    @ResponseWrapper(localName = "insertOrderShipmentResponse", targetNamespace = "http://OrderShipmentService/", className = "OrderShipmentServiceClient.InsertOrderShipmentResponse")
    @Action(input = "http://OrderShipmentService/OrderShipmentServiceImpl/insertOrderShipmentRequest", output = "http://OrderShipmentService/OrderShipmentServiceImpl/insertOrderShipmentResponse")
    public List<OrderShipment> insertOrderShipment(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderShipment arg0);

}
