
package OrderShipmentServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderShipmentService", targetNamespace = "http://OrderShipmentService/", wsdlLocation = "http://localhost:8080/OrderShipmentService?wsdl")
public class OrderShipmentService
    extends Service
{

    private final static URL ORDERSHIPMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERSHIPMENTSERVICE_EXCEPTION;
    private final static QName ORDERSHIPMENTSERVICE_QNAME = new QName("http://OrderShipmentService/", "OrderShipmentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/OrderShipmentService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERSHIPMENTSERVICE_WSDL_LOCATION = url;
        ORDERSHIPMENTSERVICE_EXCEPTION = e;
    }

    public OrderShipmentService() {
        super(__getWsdlLocation(), ORDERSHIPMENTSERVICE_QNAME);
    }

    public OrderShipmentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSHIPMENTSERVICE_QNAME, features);
    }

    public OrderShipmentService(URL wsdlLocation) {
        super(wsdlLocation, ORDERSHIPMENTSERVICE_QNAME);
    }

    public OrderShipmentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSHIPMENTSERVICE_QNAME, features);
    }

    public OrderShipmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderShipmentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderShipmentServiceImpl
     */
    @WebEndpoint(name = "OrderShipmentServicePort")
    public OrderShipmentServiceImpl getOrderShipmentServicePort() {
        return super.getPort(new QName("http://OrderShipmentService/", "OrderShipmentServicePort"), OrderShipmentServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderShipmentServiceImpl
     */
    @WebEndpoint(name = "OrderShipmentServicePort")
    public OrderShipmentServiceImpl getOrderShipmentServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://OrderShipmentService/", "OrderShipmentServicePort"), OrderShipmentServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSHIPMENTSERVICE_EXCEPTION!= null) {
            throw ORDERSHIPMENTSERVICE_EXCEPTION;
        }
        return ORDERSHIPMENTSERVICE_WSDL_LOCATION;
    }

}
