
package TransportOrderServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransportOrderService", targetNamespace = "http://TransportOrderService/", wsdlLocation = "http://localhost:8080/TransportOrderService?wsdl")
public class TransportOrderService
    extends Service
{

    private final static URL TRANSPORTORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSPORTORDERSERVICE_EXCEPTION;
    private final static QName TRANSPORTORDERSERVICE_QNAME = new QName("http://TransportOrderService/", "TransportOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TransportOrderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSPORTORDERSERVICE_WSDL_LOCATION = url;
        TRANSPORTORDERSERVICE_EXCEPTION = e;
    }

    public TransportOrderService() {
        super(__getWsdlLocation(), TRANSPORTORDERSERVICE_QNAME);
    }

    public TransportOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSPORTORDERSERVICE_QNAME, features);
    }

    public TransportOrderService(URL wsdlLocation) {
        super(wsdlLocation, TRANSPORTORDERSERVICE_QNAME);
    }

    public TransportOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSPORTORDERSERVICE_QNAME, features);
    }

    public TransportOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransportOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransportOrderServiceImpl
     */
    @WebEndpoint(name = "TransportOrderServicePort")
    public TransportOrderServiceImpl getTransportOrderServicePort() {
        return super.getPort(new QName("http://TransportOrderService/", "TransportOrderServicePort"), TransportOrderServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransportOrderServiceImpl
     */
    @WebEndpoint(name = "TransportOrderServicePort")
    public TransportOrderServiceImpl getTransportOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://TransportOrderService/", "TransportOrderServicePort"), TransportOrderServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSPORTORDERSERVICE_EXCEPTION!= null) {
            throw TRANSPORTORDERSERVICE_EXCEPTION;
        }
        return TRANSPORTORDERSERVICE_WSDL_LOCATION;
    }

}
