
package CourierServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CourierService", targetNamespace = "http://CourierService/", wsdlLocation = "http://localhost:8080/CourierService?wsdl")
public class CourierService
    extends Service
{

    private final static URL COURIERSERVICE_WSDL_LOCATION;
    private final static WebServiceException COURIERSERVICE_EXCEPTION;
    private final static QName COURIERSERVICE_QNAME = new QName("http://CourierService/", "CourierService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CourierService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COURIERSERVICE_WSDL_LOCATION = url;
        COURIERSERVICE_EXCEPTION = e;
    }

    public CourierService() {
        super(__getWsdlLocation(), COURIERSERVICE_QNAME);
    }

    public CourierService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COURIERSERVICE_QNAME, features);
    }

    public CourierService(URL wsdlLocation) {
        super(wsdlLocation, COURIERSERVICE_QNAME);
    }

    public CourierService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COURIERSERVICE_QNAME, features);
    }

    public CourierService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourierService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CourierServiceImpl
     */
    @WebEndpoint(name = "CourierServicePort")
    public CourierServiceImpl getCourierServicePort() {
        return super.getPort(new QName("http://CourierService/", "CourierServicePort"), CourierServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourierServiceImpl
     */
    @WebEndpoint(name = "CourierServicePort")
    public CourierServiceImpl getCourierServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://CourierService/", "CourierServicePort"), CourierServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COURIERSERVICE_EXCEPTION!= null) {
            throw COURIERSERVICE_EXCEPTION;
        }
        return COURIERSERVICE_WSDL_LOCATION;
    }

}
